### ISSUE TITLE
Login screen fixes

### ISSUE THREAD

**Issue by hisinbox** [bitshares/bitshares-community-ui#100]
#### Expected Behavior
- hide both PIN code fields by default
- show both PIN code fields instead of KEY FILE button, after PASSPHRASE field is fully filled 
- show KEY FILE button back when user exits the field (clicks cross or clicks outside)
- when KEY FILE button is clicked show one PASSWORD field below the button
- on Signup screen on tab Password  change text "Your account will be secured only with password" to "Faster, but less secure way to Signup. Your account will be secured only with password. Slower way to signup will better protect you" 
- with yellow font in the row just under the line of the field Confirm password insert text "This password can't be recovered, write it on paper"
- on Signup screen on tab Private key change text "You need to backup account after creating a PIN code" to "Slower, but more secure way to Signup protects your account with a combination of PIN and Backup phrase. You need to backup account after creating a PIN code"

#### Actual Behavior
- pin codes fields are shown by default

**Comment by noeminik** [comment]
on Login Screen remove: 'I accept Terms of Use' link, that should be visible only on sign up.
