### ISSUE TITLE
Market: Create widget

### ISSUE THREAD

**Issue by lapinlapin** [bitshares/bitshares-community-ui#104]
1. Create wrapper for widget;
2. Add markup of inner blocks;
3. Create components structure of them;
4. Set up communications and links between them;
5. Make a list search;
6. Make a selection of favorite markets;
7. Create filter of favourites;
8. Create sort of list fields;

**Comment by noeminik** [comment]
In the Markets section user views Markets actual information regarding volumes, prices, changes.
https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b/screen/5baa1e8fe680763fbd0761b3

On top of the lists the markets are listed, when selecting a market the list is filtered by the base currency. Prices and Volumes of the markets are presented in base (market) currency and in USD equivalent (this is a default currency and in the future user will be able to change it).

User can also filter the Markets list by favourites when marking the star. 
https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b/screen/5bb45d7aad3086a51e50baa0

See the design of elements when hoverd, selected https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b/screen/5bb45f1d3985bf32c4a54e7b

User can search the market list by typing market name or currency. Note that via search user should be able to find new markets. 
https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b/screen/5bb45dfd48a15c645a6810a1

The Markets list consists of following columns: Favourites, Name / Vol, USD | Price, USD | 24h% / 7d%

- Favourites are marked/unmarked by user when selecting the star. By default the Favourites appear on top of the list. 
- Name / Vol, USD these are market name and volume of selected currency. 
- Price, USD the price in USD
- 24h% / 7d% this is for the user to view the change, note that there are arrows next to 24h and user can increase/decrease hours to view the corresponding change. If the change has increased it should appear green in the list if decreased then red.
By default the list is sorted by Market name (Favourites are on top of the list)
Sorting can be applied to all columns.

Expanded version is a popup, that appears when user clicks on the top right icon.
the expanding icon should appear only if screen width >= 800 (according to expanded view width)

zpl://screen?pid=5ba4e8c9a61c41288762b16b&sid=5bce07b7140d6a09ac77ab38
https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b/screen/5bce07b8a49a951912f524f3

**Comment by roma219** [comment]
#107
