### ISSUE TITLE
My Open Orders desktop and mobile design

### ISSUE THREAD

**Issue by noeminik** [bitshares/bitshares-community-ui#106]
Design of Open Orders widget, where user can view active orders, cancel particular order and sort the list.

**Comment by DanielVinsa** [comment]
![open_orders_m_dark](https://user-images.githubusercontent.com/18577340/47589258-aeb27000-d979-11e8-8e36-8b73a9ce02e0.png)
![open_orders_sm_dark](https://user-images.githubusercontent.com/18577340/47589259-aeb27000-d979-11e8-8fc6-50846bdecf11.png)
Zeplin - https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b?seid=5bd36d1a13f4bb09f4e44f5d
