### ISSUE TITLE
Orders History desktop and mobile design

### ISSUE THREAD

**Issue by noeminik** [bitshares/bitshares-community-ui#108]
Order history widget allows the user to view the list of executed, canceled, expired orders that are no longer open/active.

**Comment by DanielVinsa** [comment]
![orders_history_sm](https://user-images.githubusercontent.com/18577340/47588478-4e223380-d977-11e8-94d3-d195253e1f28.png)
https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b?seid=5bd36d2e90d58d09c85ae1ce
