### ISSUE TITLE
Header Desktop Zeplin Mockup

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#111]
With different states like expanding menu for logout etc.

**Comment by dls-cipher** [comment]
Don't forget that accounts can hold more than just one account. Clicking on username should include list of all accounts owned/shared(multi-sig) by main account.

Current BitShares UI example:
![2018-10-31_0008](https://user-images.githubusercontent.com/39482961/47736340-1978e980-dca1-11e8-8bef-65fba56d9f18.png)

**Comment by DanielVinsa** [comment]
![menu_desk](https://user-images.githubusercontent.com/18577340/47898405-2c511100-de8f-11e8-984f-02b7b4ddc3e2.jpg)

**Comment by DanielVinsa** [comment]
![menu_desk](https://user-images.githubusercontent.com/18577340/47898608-0b3cf000-de90-11e8-8e50-d593c7095cbb.jpg)

**Comment by DanielVinsa** [comment]
![menu_acc](https://user-images.githubusercontent.com/18577340/47898905-47bd1b80-de91-11e8-9bfb-150f61fc0222.jpg)

**Comment by roma219** [comment]
@DanielVinsa We need zeplin for this (header and dropdown)

**Comment by roma219** [comment]
Done in zeplin
