### ISSUE TITLE
Markets widget Improvements

### ISSUE THREAD

**Issue by noeminik** [bitshares/bitshares-community-ui#114]
- expand - popup opens on the very same page, keep the background, could be darker but still visible. (currently background is black) 
- when user expands, the popup should keep the filters and search result
- popup should disappear when clicking out of popup (currently it closes only when clicked on x)
- expander icon on hover should look like this (https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b/screen/5bc4d9a9252aba5fcd76e6ec)
- on mobile, user shouldn't be able to expand the widget
- when there is scrolling, search bar appears on data, see the image

![image](https://user-images.githubusercontent.com/43628509/47612700-304cef80-da99-11e8-9877-fd6e03b56659.png)

**Comment by roma219** [comment]
#107
