### ISSUE TITLE
Private Key Backup

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#116]
We need a zeplin design for it

**Comment by DanielVinsa** [comment]
https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b?seid=5be12e4d5465486191501086

**Comment by DanielVinsa** [comment]
![backup_key](https://user-images.githubusercontent.com/18577340/48046607-777c6400-e1ae-11e8-8de1-ff54bc57c9bc.png)

**Comment by roma219** [comment]
@DanielVinsa 👍 , please also provide some desktop screens for it, at least some of them to get the general idea of modal window, switching between stages of backup etc.
