### ISSUE TITLE
Button component

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#12]
Use `Components/Button.vue`

- Styling - use tailwind classes
- Should receive props & display accordingly:
   1) :text - [String] button text
   2) :disabled - [Boolean] if button disabled or not
   3) :loading - [Boolean] if button has a loading state -> display some css loader inside (make loader a component as well)
   4) :size= - [String] optional, "normal" - default, "small" - smaller
   5) :width - [String] optional, "full" -> 100% width
   6) :type - [String] optional, "round" should make the button round

- Should $emit 'click' event on click
- Should have Styleguidist Button doc with examples
- Covered by jest unit-tests

**Comment by roma219** [comment]
@MindfulMe if you got any questions, feel free to ask here or on tg  🔨

**Comment by mindfulme** [comment]
ok, I am probably free now, the first question is whether it is necessary to make loader component separately from the button, and Stykeguidish doc must contain an explanation of used styles and the maintenance?

**Comment by roma219** [comment]
@MindfulMe for loader component for now you can use this one - https://raw.githubusercontent.com/TrustyFund/trusty-ui-vue/master/client/components/UI/Spinner.vue

As about styleguidist - the doc should contain mostly different examples of component usage - showcase for different props and how they affect button. So when someone runs a styleguidist, he can see all the possible scenarios of the button - button with loader, regular sized button, small button, full width button etc. Besides that document (just a small description) props (which prop does what) and events (what events does component emit). See [here](https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Documenting.md) for detailed info and examples.

I made one example of a button in Button.md just to show the general idea.
