### ISSUE TITLE
Order Book Questions

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#123]
1) Should columns (sum, price) be sortable?
2) Is Buying/Selling tables are scrollable separately or together?
3) How is the amount (width) of colored background calculated for each item?

**Comment by dls-cipher** [comment]
1. Yes.
2. If we can separate like binance - cool. If not, similar to current UI (lock state and unlock state for scroll) is ok.
3. To answer that question need to know first full width of column/component, then to inspect elements/rows it contains. 

Keep this as open discussion with me... I've just finished review with BBF of our first sprint :)

**Comment by roma219** [comment]
@dls-cipher 
1. Ok
2. Ok
3. To rephrase the question - am i understanding right, that the full width of a lightgreen bar represents the largest order? And all of the others green bars are calculated based on a % relatively to this order.
