### ISSUE TITLE
Order Book: Tables

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#124]
- There is a new `SortableTable` UI component, which can display headers and sort data, let's use it for both Order Book tables. See `views/Account/Portfolio.vue` for usage example.

- Upgrade `OrderBookTableItem`: zeplin design, should have `:color` prop which should apply green/red (take color from zeplin and add to tailwind config) color to `price`. Also add `:hover` (store colors in tailwind too) styles.

- Don't bother with scrollings, will take care of it later

**Comment by noeminik** [comment]
Orders book is a table of current buying / selling orders. Placed orders are matched in FIFO order by BitShares and the buyer will get the best possible price.
Orders book table consists of two parts:
Buying: user views current buying orders the Sum of BTC and the price in USD (the numbers are in green)
Selling: user views the price in USD and Sum of BTC (the numbers are in red)
First row of the table is volume of last executed order and price.

The whole widget can be collapsed by pressing the arrow next to the ‘Order Book’.
For big screens widget can be expanded.

**note**: for now we are skipping the Precision

https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b/screen/5bae4c005d5aa7853e616168

**Comment by roma219** [comment]
#142
