### ISSUE TITLE
Order book: percent bar

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#132]
Every Item in both tables in Order Book should have a colored bar which with width = % relative to the largest order amount in that table.

1) Calculate max order amount in each table
2) Send this amount as prop to each item
3) Use computed to calculate bar width amount in every item
4) Color it with some configured color in `tailwindcss.js` file

**Comment by lapinlapin** [comment]
@roma219 I made this from #124 , close please
