### ISSUE TITLE
Markets: Amount Value Shortener

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#137]
We need a helper func that is gonna convert amount number to shortened string. It should be used in Markets `Vol. USD` column. Should have unit-test for it written in `jest`.

![image](https://user-images.githubusercontent.com/4411295/47844134-a7a0bd00-ddd2-11e8-84e0-46461fd774ba.png)

**Comment by mindfulme** [comment]
@roma219 What is the maximum number of characters (numbers) the shortened string should contain before the `k` or `m`

**Comment by MindfulMe** [comment]
Two, as on the screenshot?

**Comment by roma219** [comment]
@MindfulMe not limited
