### ISSUE TITLE
Markets: external data (market cap, 52w high, 52w low)

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#175]
We need this data for each market-pair in Markets widget:
![image](https://user-images.githubusercontent.com/4411295/48359156-6ef3c400-e6ad-11e8-92d9-d75d507baeee.png)

It cannot be retrieved through BitShares, so we need to load it through some external resource. Need to figure out a way to do it for any market pair.

**Comment by ololokiras** [comment]
@roma219 may be add it like vuex module or something like that?
andjjust receive data on front?

**Comment by roma219** [comment]
Seems like we need some kind if paid account on external cryptostats site for that.

**Comment by roma219** [comment]
Closing it for now
