### ISSUE TITLE
New Order: Initialization

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#207]
1) create a Vuex module `newOrder`
2) Create a new widget `NewOrder.vue` and display in in card on a Dashboard
3) This widget should only have 2 tabs styled as here: https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b/screen/5bf076d83901503f0b583a72
Tab select should emit an event with tab name that should be stored in store
4) Asset names (displayed in tabs) should be stored as a mock data in store
5) buy/sell amounts (displayed in tabs) should stored as a mock data in store
6) Should have a `Button` component at the bottom with props setting it's background color, asset name and amount should be stored in store as well

**Comment by noeminik** [comment]
@lapinlapin  please check also the description to the new order
https://docs.google.com/document/d/1oQITHC-JazBspYU2cYwnyUYFptMNAj1IEpPcL5ya2LY/edit#heading=h.kuh4t48go8nn

**Comment by roma219** [comment]
@noeminik This task in not an actual implementation of the feature, but just a part of the markup for this widget.

**Comment by noeminik** [comment]
@roma219  ok sorry, @lapinlapin  please ignore the comment.

**Comment by dls-cipher** [comment]
> @noeminik This task in not an actual implementation of the feature, but just a part of the markup for this widget.

@roma219 What's the total ETA in hours on this markup ?

**Comment by roma219** [comment]
@dls-cipher No estimations were given, but doing code review every day - the progress is ok on this one. Required a lot of rewriting as it's a pretty complex widget...

**Comment by roma219** [comment]
#215
