### ISSUE TITLE
Order Confirmation popup

### ISSUE THREAD

**Issue by noeminik** [bitshares/bitshares-community-ui#218]
The order confirmation popup opens when user clicks on Buy/Sell button in the New Order form.
The popup should contain detailed information of the order: 
Date. Time, Trading Pair, Price, (Price in USD, if different currency), Amount, Spend / Get
There should be 2 buttons in the bottom: Confirm Order, Cancel

**Comment by DanielVinsa** [comment]
![order_confirm_pop-up](https://user-images.githubusercontent.com/18577340/49728923-75b22e80-fc8d-11e8-8daa-682981eb20ab.png)
