### ISSUE TITLE
Tabs Component

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#26]
Up to the 4 optional tabs

- Should recieve props:
1) :titles - [Array] array of string, tab titles
2) :active - [String] optional, which tab should be active when component is rendered

- Should display tab titles as a top row with selected tab highlighted
- Should have `<slot>`'s for tabs content
- Should display only tab content of the selected tab

UPD
For styling: 
- For colors (border, text color) use/create tailwind.css color variables in 'tailwind.js.' file in the root folder

**Comment by roma219** [comment]
@MindfulMe 
Should look like that:
![image](https://user-images.githubusercontent.com/4411295/46032109-634f3c80-c103-11e8-965d-22d0157775af.png)

Message me your e-mail, and i'll invite you to the zeplin project

Use [slots](https://vuejs.org/v2/guide/components-slots.html)

**Comment by mindfulme** [comment]
Also, I think slots content should come from props as tabs do

**Comment by mindfulme** [comment]
So it reasonable to have for each dynamic tab its dynamic content

**Comment by mindfulme** [comment]
I will make PR - you take a look

**Comment by roma219** [comment]
@MindfulMe Well you can't send and you shouldn't send tab content throught props - thats the whole point of slots, to pass content directly. Tab titles are here only to display itself and so that Tabs components knows the number of tabs to display.

**Comment by mindfulme** [comment]
Got it, rather when you firstly take a look
