### ISSUE TITLE
Market: issue with favorites

### ISSUE THREAD

**Issue by noeminik** [bitshares/bitshares-community-ui#265]
in Markets widget marked some pairs as favorite (starred), then tried to filter the list by favorites, but it didn't return all the results. 
![image](https://user-images.githubusercontent.com/43628509/49716079-0710a900-fc6c-11e8-8ce5-5dc554092f94.png)

![image](https://user-images.githubusercontent.com/43628509/49716107-227bb400-fc6c-11e8-8b6a-eb56528ac4a8.png)

when typing something in search bar, then user can't erase the input with one click, please add 'x' when user hovers on the search or clicks (actives) it.

**Comment by roma219** [comment]
@noeminik Please check with the current `dev`, can't reproduce the favourites issue

**Comment by roma219** [comment]
re: searchbar - #295
