### ISSUE TITLE
Empty Orders List

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#268]
Text message should be displayed inside each widget (active orders, orders history) when user has no active orders or no orders in orders history.

Make sure it is displayed after needed data is fetched, not before.

See both `ordersHistory` and `activeOrders` components and vuex-modules

**Comment by Keegan-lee** [comment]
What text would we like to display in the event that the user has no orders in their active or history views? 

I will use " No Active Orders" ( for active ) or "No Orders" ( for history ), until further notice.
