### ISSUE TITLE
Using Zeplin

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#3]
Can we use zeplin for design layouts? Would be so much more convinient.

https://zeplin.io/

**Comment by dls-cipher** [comment]
Sure. I believe tools to devs are a must, as long as final code is being per standards, and this sure looks fun even for me to learn Vue :)

@roma219 , do you have account already or we register new one ?

In both cases i suggest minimum of ['Starter'](https://zeplin.io/pricing) account @ $17 per month 

we would be having more options on exports and functionality + 3 projects

**Comment by roma219** [comment]
@dls-cipher Yeah, i'd also would like to know if it possible for our designer to use, just couldn't assign this issue to him, cause he still didn't join the project https://github.com/danielvinsa

In case he agrees, it would be great if you register dedicated account for it, 'Starter' would be totally sufficient.

**Comment by roma219** [comment]
@danielvinsa

**Comment by DanielVinsa** [comment]
okay, but using Zeplin will take time for studying. so i'm ready to try it

**Comment by dls-cipher** [comment]
I'll register account and subscribe to Starter as mentioned.

**Comment by roma219** [comment]
@DanielVinsa Great, i think you'll enjoy it - it's a modern tool that is made really well. And it's gonna make managing layouts for us really convenient.

**Comment by DanielVinsa** [comment]
Send me please login/password for Zeplin

**Comment by DanielVinsa** [comment]
> @DanielVinsa Great, i think you'll enjoy it - it's a modern tool that is made really well. And it's gonna make managing layouts for us really convenient.

How can i log in to Zeplin account?

**Comment by roma219** [comment]
@dls-cipher I think you can create a project in Zepplin and invite @DanielVinsa (as well as the rest of the team) to the project
