### ISSUE TITLE
Fix the ui of Scrolling when on hover

### ISSUE THREAD

**Issue by noeminik** [bitshares/bitshares-community-ui#309]
fix the scrolling on hover
currently it looks like this
on hover should be as following
width: 3 px
border-radius: 1.5px

![image](https://user-images.githubusercontent.com/43628509/50109689-f48d0580-0251-11e9-83a1-11bee3d8819f.png)

**Comment by roma219** [comment]
Done in https://github.com/bitshares/bitshares-community-ui/commit/edbc4917d07fcf7e46702d6bdf1942f194e24605
