### ISSUE TITLE
New Order Improvements

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#318]
1) Trim number after the `.` after calculated precised amount right before placing order
2) Make max length of inputs 9 - should be probably done throught some directive and modifying `SimpleInput`, or in actions when setting price/get/spent. e.g.:
`parseFloat(String(0.92342783462364234).substring(0,9))` (#314)
3) Prevent placing order when user doesn't have anough BTS & show some kind of indicator about it. Also when spending BTS subtract bts fee from max amount available.
4) 
![image](https://user-images.githubusercontent.com/4411295/50136066-8ffc9580-02a7-11e9-8be3-2df5ac2247a9.png) (#315)
6) Market order doesn't work properly in Sell mode
![image](https://user-images.githubusercontent.com/4411295/50372436-54cbd080-05df-11e9-988a-281c19220951.png)

**Comment by roma219** [comment]
re: 9
Probably use something like this directive and apply it via props (similar to currently used `restrict` directive):
http://www.webspeaks.in/2017/07/custom-directives-in-vuejs.html

**Comment by hisinbox** [comment]
please shift volume fields a bit away (left/right) from the price field - to make sure that long volume entries do not intersect the circle (see the original mockup) @roma219 @plapinp17

**Comment by hisinbox** [comment]
also I noticed that price field (and circles) are to close to the button - there must be more space between the button and the circle @roma219 @plapinp17

**Comment by youaresofunny** [comment]
@hisinbox 
Please make some separate issue if comments are actual
This task wasn't about markup)
