### ISSUE TITLE
Settings mobile unexpected hobbit

### ISSUE THREAD

**Issue by noeminik** [bitshares/bitshares-community-ui#328]
on mobile view when opening the menu burger there is HOBB1T word
 
![image](https://user-images.githubusercontent.com/43628509/50222778-b6f3be00-03b2-11e9-8da3-5a967ff6dfcd.png)

**Comment by roma219** [comment]
@Keegan-lee There should be a username there instead

**Comment by roma219** [comment]
https://github.com/bitshares/bitshares-community-ui/commit/0f44879204257a2dfd248a85a1cd0146a55447e6
