### ISSUE TITLE
Deposit: copy address is not responding

### ISSUE THREAD

**Issue by noeminik** [bitshares/bitshares-community-ui#340]
on Deposit, after choosing the token, copy address button is not copying the address

![image](https://user-images.githubusercontent.com/43628509/50340221-9bfc8780-0533-11e9-8f20-c0158146a691.png)

**Comment by roma219** [comment]
https://github.com/bitshares/bitshares-community-ui/commit/e06c79f5f1a665e27b4d6ff2e55f8d5d028137ec

**Comment by roma219** [comment]
@lapinlapin Should copy to clipboard differently. See `Singup.vue` for example.
