### ISSUE TITLE
Orders history is empty

### ISSUE THREAD

**Issue by noeminik** [bitshares/bitshares-community-ui#342]
though there have been orders placed with the account and application used to show the data, but currently it says no order history

**Comment by roma219** [comment]
@noeminik account name? Probably a bitshares node bug, happens sometimes

**Comment by lapinlapin** [comment]
no actual
![image](https://user-images.githubusercontent.com/6066637/50487809-bbeaea00-0a10-11e9-8a85-4dbbe2ae9cd3.png)
