### ISSUE TITLE
Transfer: in the confirmation popup include also MEMO

### ISSUE THREAD

**Issue by noeminik** [bitshares/bitshares-community-ui#350]
in the transfer confirmation include also memo
and change the button name to 'CONFIRM TRANSFER'
![image](https://user-images.githubusercontent.com/43628509/50394092-73170500-0774-11e9-9ab8-178da2b74c3b.png)

**Comment by lapinlapin** [comment]
no actual

**Comment by noeminik** [comment]
fixed
