### ISSUE TITLE
New order: long asset name

### ISSUE THREAD

**Issue by noeminik** [bitshares/bitshares-community-ui#351]
if the asset has long name it doesn't fit properly in the tab

![image](https://user-images.githubusercontent.com/43628509/50394947-77deb780-077a-11e9-8b31-b25c97e02dd1.png)

**Comment by lapinlapin** [comment]
we removed the prefixes in the #355 , I think the problem with long tickers is solved. if you agree close please

**Comment by noeminik** [comment]
issue is fixed within other issue, not merged yet.
