### ISSUE TITLE
issue with Order confirmation view on mobile

### ISSUE THREAD

**Issue by noeminik** [bitshares/bitshares-community-ui#356]
currently order confirmation looks like
![image](https://user-images.githubusercontent.com/43628509/50421202-2efc3100-0856-11e9-9036-e6691d975576.png)

but should be as designed:
https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b/screen/5c0580f3abb793023a189de3

**Comment by lapinlapin** [comment]
fixed #376
