### ISSUE TITLE
Unlock Account popup ui

### ISSUE THREAD

**Issue by noeminik** [bitshares/bitshares-community-ui#357]
![image](https://user-images.githubusercontent.com/43628509/50419901-ce1c2b00-084c-11e9-8eb8-d20fe9ff6c57.png)
The popup should look as in design, check the size and text alignment is zeplin ->
https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b/screen/5c115292a1a063afdb4b31a3

when opening the unlock account popup the one behind should not be visible.

**Comment by youaresofunny** [comment]
@noeminik 
https://github.com/bitshares/bitshares-community-ui/issues/354
Here, same unlock popup 
> must  'cover' the popup underneath.


So, what is right one behaviour?

**Comment by noeminik** [comment]
@youaresofunny  make the unlock account popup to cover the address confirm popup (which is 480x480px), so it's not visible.
