### ISSUE TITLE
Markets monitor UI

### ISSUE THREAD

**Issue by hisinbox** [bitshares/bitshares-community-ui#36]
Provide a user-friendly interface to track markets performance stats in minimised and expanded views

**Comment by roma219** [comment]
https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b/screen/5baa1e8fe680763fbd0761b3

**Comment by sschiessl-bcp** [comment]
Zeplin is private, please post Screenshots in the issue once you have agreed upon a UI
