### ISSUE TITLE
Account: Deposit/Withdraw buttons don't work on Expanded Account window

### ISSUE THREAD

**Issue by hisinbox** [bitshares/bitshares-community-ui#363]

**Comment by roma219** [comment]
@lapinlapin 
Withdraw - make WITHDRAW button active only for correct assets (see `Withdraw` list generation) and disable the others. Click WITHDRAW -> Open withdraw modal and select corresponding asset.

Deposit - clicking DEPOSIT just opens the general Deposit modal.
