### ISSUE TITLE
Scrolling conflict in Orders history

### ISSUE THREAD

**Issue by noeminik** [bitshares/bitshares-community-ui#369]
Scrolling conflict in Orders history.
in mobile view the widget scroll and general scroll conflict. 
![image](https://user-images.githubusercontent.com/43628509/50472943-7dcfd500-09d4-11e9-9473-3895f6d56da7.png)

leave only one general scroll, but make the widget name (in current case History) on top, so whenever user wants can collapse the widget.

**Comment by roma219** [comment]
@noeminik There is no conflict, there is simply 2 scroll bars. Please explain desired behaviour more thoughtfully.

**Comment by noeminik** [comment]
@roma219 this is fixed on dev
