### ISSUE TITLE
New Order: on Market tab the price should be: market

### ISSUE THREAD

**Issue by noeminik** [bitshares/bitshares-community-ui#380]
New Order widget
in the Limit tab show the Last best price (in the circle)

in Market tab the price in the circle should be MARKET and not 0

![image](https://user-images.githubusercontent.com/43628509/50539461-1c596300-0b9a-11e9-96bf-f38b5a666682.png)

price is not fitting in the circle
![image](https://user-images.githubusercontent.com/43628509/50541169-42dac680-0bb9-11e9-94f4-ca63c49d9bc7.png)

**Comment by roma219** [comment]
Non-existent
