### ISSUE TITLE
Pin of secure key account should consist of chars as password

### ISSUE THREAD

**Issue by noeminik** [bitshares/bitshares-community-ui#385]
currently on our ui users may have PIN that consists of only numbers, but shouldn't be so, should behave as password.
this should be fixed on signup and backup screens.

**Comment by roma219** [comment]
@noeminik It was planned as numbers only and implemented so.

**Comment by noeminik** [comment]
@roma219 ok, but how should do the accounts that were created on bitshares and their pin is a password, so those users wont be able to backup their account using our ui. But here we need ‘product’ decision and then only implementation. @hisinbox

**Comment by roma219** [comment]
@noeminik When user logs in into our App, he creates a new PIN code, so it won't be a problem,
