### ISSUE TITLE
Integrate vuex-bitshares

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#4]
https://github.com/TrustyFund/vuex-bitshares

Create separate branch in it named "bitshares-community-ui"

**Comment by roma219** [comment]
@dls-cipher As you know, we have an existing library, `vuex-bitshares` (https://github.com/TrustyFund/vuex-bitshares), which already has a lot of functionality that is gonna be useful for this project. But the thing is, during the development we are gonna make modifications to it/make pull requests/tests etc, which raises the question of how we gonna track time for it, if it happens in another repo. I propose the fork is being made from it and placed into Bitshares github group. This way it is gonna be all clear for everyone. Basically we will have two repos in Bitshares group instead of one.

@youaresofunny @hisinbox

**Comment by clockworkgr** [comment]
I was gonna suggest the same thing... I want to add vuex-bitshares as a submodule to integrate and use in Beet.

So definitely worth forking over to the bitshares org repo imho since multiple bitshares org projects are gonna use it. @abitmore , @xeroc  ok with you guys?

**Comment by abitmore** [comment]
Looks like it's MIT licensed. I'm OK with forking.

**Comment by dls-cipher** [comment]
@clockworkgr can you please do the honor of forking and just add me as an admin so I can manage it with the guys during worker (possibly after) ?

Thanks both of you @abitmore and @clockworkgr

**Comment by clockworkgr** [comment]
Forked: https://github.com/bitshares/vuex-bitshares
