### ISSUE TITLE
Order book desktop window design desktop min/exp views

### ISSUE THREAD

**Issue by hisinbox** [bitshares/bitshares-community-ui#46]
Clean and simple UI with the list of all buy and sell orders, with visual representation of orders volume at each price level, ability to change price step, minimised and expanded versions

**Comment by DanielVinsa** [comment]
Order Book dark mockup are up to date:
https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b?seid=5bae4dc03ab0ee435fbf98a0

**Comment by DanielVinsa** [comment]
![order_book_dark_max](https://user-images.githubusercontent.com/18577340/47798828-80021400-dd42-11e8-88f6-542b8c3667da.png)
![order_book_dark_mid](https://user-images.githubusercontent.com/18577340/47798829-809aaa80-dd42-11e8-85ca-a17001eaf078.png)
![order_book_dark_min](https://user-images.githubusercontent.com/18577340/47798831-809aaa80-dd42-11e8-9c52-dd2c1243a2db.png)
