### ISSUE TITLE
Dev branch

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#49]
Guys, what do you think if we got another branch for current development works (`dev`) that could be supervised by me and @youaresofunny, as we gonna accept PRs into it with work for current issues. And that `dev` branch would be merged into `staging` once every other week or so (aka our internal release) with your reviews? Basically we gonna ship PRs to staging in a batch. I think that would be convenient for everybody involved.

**Comment by hisinbox** [comment]
as discussed I think it's a good idea

**Comment by roma219** [comment]
@dls-cipher ok with this?

**Comment by dls-cipher** [comment]
Very ok.

**Comment by roma219** [comment]
👍
