### ISSUE TITLE
Authentication question

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#53]
Should we make an app blocked from unauthorized user? So basically the user is redirected to login page if he is not authorized. Or the user always has access to main dashboard, and authorization provides additional features to him

**Comment by hisinbox** [comment]
suggest that we follow the same approach as in the bitshares UI - ie dashboard available, trading withdrawal only after account is unlocked (second option @roma219 suggested)

**Comment by dls-cipher** [comment]
Ill agree on this one with @roma219 

I believe that so many open options for user who is not authenticated will just lead to more chaos when it comes to ease of use(UX) in this case.

@roma219 - hit as you've suggested: non-auth user -> force [login/register]

If this was only informational issue, please confirm and close the issue.
