### ISSUE TITLE
Basic Portfolio Markup

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#57]
Portfolio is a widget that should display a basic table with asset names and token amount information. Take into account that additional columns will be added in future. Create `Portfolio` and `PortfolioItem` components. This task is for markup only. Portfolio card should be placed in the `Dashboard` component. Use mock data for display.

**Comment by roma219** [comment]
@MindfulMe Use `css-grid` for table layout

**Comment by mindfulme** [comment]
ok

**Comment by mindfulme** [comment]
there is something with input component, it causes errors

**Comment by mindfulme** [comment]
just when opening components page

**Comment by roma219** [comment]
@MindfulMe Remove input components from `Components.vue`. Place `Portfolio` component into `Dashboard`

**Comment by mindfulme** [comment]
I did so

**Comment by mindfulme** [comment]
@roma219 Is it okay to pass table data as props or the data will come just from some other origin like api?

**Comment by DanielVinsa** [comment]
![acc_portfolio_big1_dark](https://user-images.githubusercontent.com/18577340/47800728-4af7c080-dd46-11e8-8b5f-54ad1e2cd4ef.png)
![account_dark_mid1](https://user-images.githubusercontent.com/18577340/47800731-4b905700-dd46-11e8-9fa6-4c24ddb59fad.png)
![account_dark_mid2](https://user-images.githubusercontent.com/18577340/47800733-4b905700-dd46-11e8-8338-06aae39828e7.png)
![account_dark_mid3](https://user-images.githubusercontent.com/18577340/47800735-4c28ed80-dd46-11e8-9a95-3e3bf91192ce.png)
![account_dark_min](https://user-images.githubusercontent.com/18577340/47800738-4cc18400-dd46-11e8-8504-309db17f9f6a.png)
