### ISSUE TITLE
Mobile footer

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#73]
- Should be locked to bottom on small screen width - use tailwind
- Should generate bottom buttons dynamically from an array
- Should emit an event on button click

See Zeplin for design

**Comment by mindfulme** [comment]
I assume this is the design: https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b/screen/5bbe1598252aba5fcd2f2b9d

**Comment by mindfulme** [comment]
Also, should I write jest unit tests for the component?
