### ISSUE TITLE
Setup CI/CD

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#8]
We'll need ability to deploy to staging and production, as well as separate branch deploys.

**Comment by youaresofunny** [comment]
https://travis-ci.org/bitshares/bitshares-community-ui
https://travis-ci.org/bitshares/vuex-bitshares

We need admin (or team member) here, to activate repos on Travis

@dls-cipher @roma219

**Comment by clockworkgr** [comment]
Activated for vuex bitshares.... @dls-cipher either you have to do community repo or give me admin to it so I can sort it out

**Comment by dls-cipher** [comment]
Sent request for bitshares-community-ui to BitShares GitHub admin (activation from Travis) - @abitmore please look into it.

@clockworkgr - added as repo Admin. Thanks for help/heads-up, much appreciated.

**Comment by clockworkgr** [comment]
ok...enabled community-ui too

**Comment by youaresofunny** [comment]
We need to setup webhook for this repo to http://staging-ui.trusty.apasia.tech:8000/payload (read pull requests and pushes permissions).
Please also chose and PM me entered secret, so i will setup it on server ( to ensure that only github can init build processes)

@dls-cipher @clockworkgr

**Comment by youaresofunny** [comment]
It works, thx!
