### ISSUE TITLE
Account: Hide small assets

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#82]
Link button that hides small assets/shows all assets in click

**Comment by roma219** [comment]
@noeminik @hisinbox 
What is the intended behaviour, what assets should be hidden when "hiding small assets"?

**Comment by noeminik** [comment]
@roma219  if the amount is less than 5$ then it's considered as small asset, so when clicked on hide small assets those that are <5$ should be hidden.
