### ISSUE TITLE
Markets: Improve and stylize Tabs component

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#84]
Need to add options/styles to Tabs component to make it similar to design

See
https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b/screen/5bb45f1d3985bf32c4a54e7b

**Comment by sschiessl-bcp** [comment]
Zeplin is private, please post Screenshots in the issue once you have agreed upon a UI

**Comment by roma219** [comment]
#107
