### ISSUE TITLE
Table Sortable Header Item Component

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#86]
- Recieves 1 prop `:sort`, the can have values `asc`, `desc` or null
- Receives title through slot
- Displays 2 arrows next to title
- Display sorted state
- Design: https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b/screen/5bc4d9a9c1de410a38d264ad
[icons_sort_arrow.zip](https://github.com/bitshares/bitshares-community-ui/files/2496208/icons_sort_arrow.zip)

**Comment by roma219** [comment]
@MindfulMe Please do this task next

**Comment by mindfulme** [comment]
@roma219 Is there a way to get the 2 arrows icon from Zeplin? The component is almost ready need only the icon.

**Comment by mindfulme** [comment]
or I just don't have the access to them in Zeplin (exporting)

**Comment by roma219** [comment]
@MindfulMe 
Component:
![image](https://user-images.githubusercontent.com/4411295/47198550-87eeab00-d375-11e8-858c-7a26627c9ceb.png)

Icon - you need 1 arrow icon, and just use it 2 times, ask @DanielVinsa for it

**Comment by DanielVinsa** [comment]
[icons_sort_arrow.zip](https://github.com/bitshares/bitshares-community-ui/files/2496212/icons_sort_arrow.zip)
