### ISSUE TITLE
Account: scrolling table

### ISSUE THREAD

**Issue by roma219** [bitshares/bitshares-community-ui#96]
![account_max_dark_blnc](https://user-images.githubusercontent.com/18577340/47899119-ef3a4e00-de91-11e8-84f0-0f07c6ebbd19.png)
![account_mid_dark_blnc](https://user-images.githubusercontent.com/18577340/47899120-ef3a4e00-de91-11e8-8fbf-e5c11a9040e2.png)
![account_mid_dark_half](https://user-images.githubusercontent.com/18577340/47899121-ef3a4e00-de91-11e8-949f-6d4fad9671b9.png)
![account_mid_dark_prc](https://user-images.githubusercontent.com/18577340/47899219-46d8b980-de92-11e8-82e0-dfdccec93c4d.png)
![account_min_dark](https://user-images.githubusercontent.com/18577340/47899124-efd2e480-de91-11e8-99b2-8c362b43ca2e.png)

Account widget's table should be able to scroll through it's body (without header)

**Comment by DanielVinsa** [comment]
![account_sm_dark](https://user-images.githubusercontent.com/18577340/47589462-3ef0b500-d97a-11e8-99c5-161bd1bdefb3.png)

**Comment by noeminik** [comment]
Widget size is 494x494, if there are many rows then scrolling appears.

**Comment by roma219** [comment]
@noeminik @DanielVinsa  That seems too big of a width. If it is 1/3 of a dashboard width, then dashboard is 1500px? Cannot be true, that is way too big for desktop. 494px is about 1.5x more than mobile max.

**Comment by DanielVinsa** [comment]
On mobile phone it decrease proportionally

**Comment by roma219** [comment]
@DanielVinsa Proportional to what? Right now it is not suitable even for desktop.

**Comment by DanielVinsa** [comment]
Сделаю вариант под самый популярный - 1366x768
http://prntscr.com/ldfoxa

**Comment by roma219** [comment]
@DanielVinsa Maybe 1280 or even less (for the width of the dashboard). The problem is that we gonna have to switch to mobile mode ( = 1 widget on screen) if browser screen size is less than 1366. Or we need to come up with some solutaion for in-between situations (mobile and full-width)
